python examples/wanvideo/visualize_cross_attention.py \
  --prompt "a video of a pink rose blooming" \
  --out_dir ./visualizations/pink_rose_blooming \
  --num_mega_blocks 6 \
  --stride 5 \
  --start_block 0 \
  --frame_index 0 \
  --frame_view both \
  --upsample_to_pixel \
  --aggregation full \
  --num_inference_steps 50 \
  --local_model_path /workspace/autodl-tmp/models/clora-wan
